name: OG CI

on:
  pull_request:
    branches: [main]

jobs:
  next:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
    - name: Install Deps (immutable)
      run: pnpm install --no-frozen-lockfile
    - name: Build
      run: pnpm build
    - name: Run Unit Test
      run: pnpm test:ci